using static PakMaster.Infrastructure.Platform.DependencyManager;

namespace PakMaster.Core.Constants
{
    public static class MsiErrorRegistry
    {
        public static readonly Dictionary<int, (string Name, string Description, ProcessResult Category)> Errors = new()
        {
            { 0, ("ERROR_SUCCESS", "The action completed successfully.", ProcessResult.Success) },
            { 13, ("ERROR_INVALID_DATA", "The data is invalid.", ProcessResult.Failed) },
            { 87, ("ERROR_INVALID_PARAMETER", "One of the parameters was invalid.", ProcessResult.Failed) },
            { 120, ("ERROR_CALL_NOT_IMPLEMENTED", "Custom action attempted to call a function.", ProcessResult.Failed) },
            { 1259, ("ERROR_APPHELP_BLOCK", "Product is incompatible and user chose not to install.", ProcessResult.UserCancelled) },
            { 1601, ("ERROR_INSTALL_SERVICE_FAILURE", "The Windows Installer service couldn't be accessed.", ProcessResult.Failed) },
            { 1602, ("ERROR_INSTALL_USEREXIT", "The user canceled installation.", ProcessResult.UserCancelled) },
            { 1603, ("ERROR_INSTALL_FAILURE", "A fatal error occurred during installation.", ProcessResult.Failed) },
            { 1604, ("ERROR_INSTALL_SUSPEND", "Installation suspended, incomplete.", ProcessResult.Failed) },
            { 1605, ("ERROR_UNKNOWN_PRODUCT", "This action is only valid for products currently installed.", ProcessResult.Failed) },
            { 1606, ("ERROR_UNKNOWN_FEATURE", "The feature identifier isn't registered.", ProcessResult.Failed) },
            { 1607, ("ERROR_UNKNOWN_COMPONENT", "The component identifier isn't registered.", ProcessResult.Failed) },
            { 1608, ("ERROR_UNKNOWN_PROPERTY", "This is an unknown property.", ProcessResult.Failed) },
            { 1609, ("ERROR_INVALID_HANDLE_STATE", "The handle is in an invalid state.", ProcessResult.Failed) },
            { 1610, ("ERROR_BAD_CONFIGURATION", "The configuration data for this product is corrupt.", ProcessResult.Failed) },
            { 1611, ("ERROR_INDEX_ABSENT", "The component qualifier not present.", ProcessResult.Failed) },
            { 1612, ("ERROR_INSTALL_SOURCE_ABSENT", "The installation source for this product isn't available.", ProcessResult.Failed) },
            { 1613, ("ERROR_INSTALL_PACKAGE_VERSION", "This package requires a newer version of Windows Installer.", ProcessResult.Failed) },
            { 1614, ("ERROR_PRODUCT_UNINSTALLED", "The product is uninstalled.", ProcessResult.Failed) },
            { 1615, ("ERROR_BAD_QUERY_SYNTAX", "The SQL query syntax is invalid or unsupported.", ProcessResult.Failed) },
            { 1616, ("ERROR_INVALID_FIELD", "The record field does not exist.", ProcessResult.Failed) },
            { 1618, ("ERROR_INSTALL_ALREADY_RUNNING", "Another installation is already in progress.", ProcessResult.InstallerLocked) },
            { 1619, ("ERROR_INSTALL_PACKAGE_OPEN_FAILED", "This installation package couldn't be opened or verified.", ProcessResult.Failed) },
            { 1620, ("ERROR_INSTALL_PACKAGE_INVALID", "This installation package couldn't be opened / invalid layout.", ProcessResult.Failed) },
            { 1621, ("ERROR_INSTALL_UI_FAILURE", "Error starting the Windows Installer service user interface.", ProcessResult.Failed) },
            { 1622, ("ERROR_INSTALL_LOG_FAILURE", "There was an error opening installation log file.", ProcessResult.Failed) },
            { 1623, ("ERROR_INSTALL_LANGUAGE_UNSUPPORTED", "This language of this package isn't supported.", ProcessResult.Failed) },
            { 1624, ("ERROR_INSTALL_TRANSFORM_FAILURE", "There was an error applying transforms.", ProcessResult.Failed) },
            { 1625, ("ERROR_INSTALL_PACKAGE_REJECTED", "This installation is forbidden by system policy.", ProcessResult.Failed) },
            { 1626, ("ERROR_FUNCTION_NOT_CALLED", "The function couldn't be executed.", ProcessResult.Failed) },
            { 1627, ("ERROR_FUNCTION_FAILED", "The function failed during execution.", ProcessResult.Failed) },
            { 1628, ("ERROR_INVALID_TABLE", "An invalid or unknown table was specified.", ProcessResult.Failed) },
            { 1629, ("ERROR_DATATYPE_MISMATCH", "The data supplied is the wrong type.", ProcessResult.Failed) },
            { 1630, ("ERROR_UNSUPPORTED_TYPE", "Data of this type isn't supported.", ProcessResult.Failed) },
            { 1631, ("ERROR_CREATE_FAILED", "The Windows Installer service failed to start.", ProcessResult.Failed) },
            { 1632, ("ERROR_INSTALL_TEMP_UNWRITABLE", "The Temp folder is either full or inaccessible.", ProcessResult.Failed) },
            { 1633, ("ERROR_INSTALL_PLATFORM_UNSUPPORTED", "This installation package isn't supported on this platform.", ProcessResult.PlatformUnsupported) },
            { 1634, ("ERROR_INSTALL_NOTUSED", "Component isn't used on this machine.", ProcessResult.Failed) },
            { 1635, ("ERROR_PATCH_PACKAGE_OPEN_FAILED", "This patch package couldn't be opened.", ProcessResult.Failed) },
            { 1636, ("ERROR_PATCH_PACKAGE_INVALID", "This patch package couldn't be opened / invalid.", ProcessResult.Failed) },
            { 1637, ("ERROR_PATCH_PACKAGE_UNSUPPORTED", "This patch package can't be processed by Windows Installer.", ProcessResult.Failed) },
            { 1638, ("ERROR_PRODUCT_VERSION", "Another version of this product is already installed.", ProcessResult.Success) },
            { 1639, ("ERROR_INVALID_COMMAND_LINE", "Invalid command line argument.", ProcessResult.Failed) },
            { 1640, ("ERROR_INSTALL_REMOTE_DISALLOWED", "User isn't permitted to install from a server terminal role.", ProcessResult.Failed) },
            { 1641, ("ERROR_SUCCESS_REBOOT_INITIATED", "The installer has initiated a restart.", ProcessResult.SuccessRebootRequired) },
            { 1642, ("ERROR_PATCH_TARGET_NOT_FOUND", "The installer can't install the upgrade patch.", ProcessResult.Failed) },
            { 1643, ("ERROR_PATCH_PACKAGE_REJECTED", "The patch package isn't permitted by system policy.", ProcessResult.Failed) },
            { 1644, ("ERROR_INSTALL_TRANSFORM_REJECTED", "One or more customizations aren't permitted.", ProcessResult.Failed) },
            { 1645, ("ERROR_INSTALL_REMOTE_PROHIBITED", "Remote Desktop Connection installations are disallowed.", ProcessResult.Failed) },
            { 1646, ("ERROR_PATCH_REMOVAL_UNSUPPORTED", "The patch package isn't a removable patch package.", ProcessResult.Failed) },
            { 1647, ("ERROR_UNKNOWN_PATCH", "The patch isn't applied to this product.", ProcessResult.Failed) },
            { 1648, ("ERROR_PATCH_NO_SEQUENCE", "No valid sequence could be found for the set of patches.", ProcessResult.Failed) },
            { 1649, ("ERROR_PATCH_REMOVAL_DISALLOWED", "Patch removal was disallowed by policy.", ProcessResult.Failed) },
            { 1650, ("ERROR_INVALID_PATCH_XML", "The XML patch data is invalid.", ProcessResult.Failed) },
            { 1651, ("ERROR_PATCH_MANAGED_ADVERTISED_PRODUCT", "Failed to apply patch for application in advertised state.", ProcessResult.Failed) },
            { 1652, ("ERROR_INSTALL_SERVICE_SAFEBOOT", "Windows Installer isn't accessible when in Safe Mode.", ProcessResult.Failed) },
            { 1653, ("ERROR_ROLLBACK_DISABLED", "Rollback has been disabled; multi-package transaction failed.", ProcessResult.Failed) },
            { 1654, ("ERROR_INSTALL_REJECTED", "The app is unsigned or unsupported on this version of Windows.", ProcessResult.PlatformUnsupported) },
            { 3010, ("ERROR_SUCCESS_REBOOT_REQUIRED", "A restart is required to complete the install.", ProcessResult.SuccessRebootRequired) }
        };
    }
}