//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakMaster.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PakMaster.UI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOPER.
        /// </summary>
        public static string About_Lbl_Developer {
            get {
                return ResourceManager.GetString("About_Lbl_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LICENSE.
        /// </summary>
        public static string About_Lbl_License {
            get {
                return ResourceManager.GetString("About_Lbl_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string About_Lbl_Name {
            get {
                return ResourceManager.GetString("About_Lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS ARCHITECTURE.
        /// </summary>
        public static string About_Lbl_OsArchitecture {
            get {
                return ResourceManager.GetString("About_Lbl_OsArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARGET FRAMEWORK.
        /// </summary>
        public static string About_Lbl_TargetFramework {
            get {
                return ResourceManager.GetString("About_Lbl_TargetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSION.
        /// </summary>
        public static string About_Lbl_Version {
            get {
                return ResourceManager.GetString("About_Lbl_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Information.
        /// </summary>
        public static string About_Section_ApplicationInformation {
            get {
                return ResourceManager.GetString("About_Section_ApplicationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support the Developer.
        /// </summary>
        public static string About_Section_SupportTheDeveloper {
            get {
                return ResourceManager.GetString("About_Section_SupportTheDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this app has helped you out, or if you&apos;re just feeling generous today, any tips are appreciated. I don&apos;t have a company paying me to build these tools; I do all of this in my free time. Because of that, any support I get comes entirely from the great people who use my apps..
        /// </summary>
        public static string About_Section_SupportTheDeveloper_Desc {
            get {
                return ResourceManager.GetString("About_Section_SupportTheDeveloper_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string AESKeys_GUID {
            get {
                return ResourceManager.GetString("AESKeys_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX.
        /// </summary>
        public static string AESKeys_HEX {
            get {
                return ResourceManager.GetString("AESKeys_HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repak AES Key.
        /// </summary>
        public static string AESKeys_RepakAESKey {
            get {
                return ResourceManager.GetString("AESKeys_RepakAESKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AESKeys_Save {
            get {
                return ResourceManager.GetString("AESKeys_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES Keys.
        /// </summary>
        public static string AESKeys_Title {
            get {
                return ResourceManager.GetString("AESKeys_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZenTools AES Key.
        /// </summary>
        public static string AESKeys_ZenToolsAESKey {
            get {
                return ResourceManager.GetString("AESKeys_ZenToolsAESKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update for Repak is available ({0} -&gt; {1}).
        ///
        ///Would you like to update it now?.
        /// </summary>
        public static string AnUpdateForRepakIsAvailable {
            get {
                return ResourceManager.GetString("AnUpdateForRepakIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update for Retoc is available ({0} -&gt; {1}).
        ///
        ///Would you like to update it now?.
        /// </summary>
        public static string AnUpdateForRetocIsAvailable {
            get {
                return ResourceManager.GetString("AnUpdateForRetocIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of this application is already running..
        /// </summary>
        public static string App_Msg_AlreadyRunning_Desc {
            get {
                return ResourceManager.GetString("App_Msg_AlreadyRunning_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Already Running.
        /// </summary>
        public static string App_Msg_AlreadyRunning_Title {
            get {
                return ResourceManager.GetString("App_Msg_AlreadyRunning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error occurred and the crash reporter could not be started.
        ///
        ///Original Error: {0}
        ///
        ///Launch Error: {1}.
        /// </summary>
        public static string App_Msg_CrashReporterError_Desc {
            get {
                return ResourceManager.GetString("App_Msg_CrashReporterError_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Application Crash.
        /// </summary>
        public static string App_Msg_CrashReporterError_Title {
            get {
                return ResourceManager.GetString("App_Msg_CrashReporterError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical setup error occurred during startup..
        /// </summary>
        public static string App_Msg_StartupError_Desc {
            get {
                return ResourceManager.GetString("App_Msg_StartupError_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization Error.
        /// </summary>
        public static string App_Msg_StartupError_Title {
            get {
                return ResourceManager.GetString("App_Msg_StartupError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying final touches....
        /// </summary>
        public static string App_ReportProgress_Final {
            get {
                return ResourceManager.GetString("App_ReportProgress_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing application settings....
        /// </summary>
        public static string App_ReportProgress_InitAppSettings {
            get {
                return ResourceManager.GetString("App_ReportProgress_InitAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing dependency service....
        /// </summary>
        public static string App_ReportProgress_InitDepedencyService {
            get {
                return ResourceManager.GetString("App_ReportProgress_InitDepedencyService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing language manager....
        /// </summary>
        public static string App_ReportProgress_InitLanguageService {
            get {
                return ResourceManager.GetString("App_ReportProgress_InitLanguageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing diagnostics....
        /// </summary>
        public static string App_ReportProgress_InitLogging {
            get {
                return ResourceManager.GetString("App_ReportProgress_InitLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing telemetry service....
        /// </summary>
        public static string App_ReportProgress_InitTelemetryService {
            get {
                return ResourceManager.GetString("App_ReportProgress_InitTelemetryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing theme builder....
        /// </summary>
        public static string App_ReportProgress_InitThemeService {
            get {
                return ResourceManager.GetString("App_ReportProgress_InitThemeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading tool configurations....
        /// </summary>
        public static string App_ReportProgress_InitToolConfigs {
            get {
                return ResourceManager.GetString("App_ReportProgress_InitToolConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string AppSettings_Btn_CheckForUpdates {
            get {
                return ResourceManager.GetString("AppSettings_Btn_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App Config Folder.
        /// </summary>
        public static string AppSettings_Btn_OpenAppConfigFolder {
            get {
                return ResourceManager.GetString("AppSettings_Btn_OpenAppConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs Folder.
        /// </summary>
        public static string AppSettings_Btn_OpenLogsFolder {
            get {
                return ResourceManager.GetString("AppSettings_Btn_OpenLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Position.
        /// </summary>
        public static string AppSettings_Btn_ResetPosition {
            get {
                return ResourceManager.GetString("AppSettings_Btn_ResetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string AppSettings_Btn_ResetSettings {
            get {
                return ResourceManager.GetString("AppSettings_Btn_ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the accent color utilized across the application..
        /// </summary>
        public static string AppSettings_Desc_AccentColor {
            get {
                return ResourceManager.GetString("AppSettings_Desc_AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the application window pinned above all other open windows..
        /// </summary>
        public static string AppSettings_Desc_AlwaysOnTop {
            get {
                return ResourceManager.GetString("AppSettings_Desc_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually check for the latest version immediately..
        /// </summary>
        public static string AppSettings_Desc_CheckForUpdates {
            get {
                return ResourceManager.GetString("AppSettings_Desc_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the application up to date by checking for updates on startup..
        /// </summary>
        public static string AppSettings_Desc_CheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("AppSettings_Desc_CheckForUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a log file to help track down application issues..
        /// </summary>
        public static string AppSettings_Desc_EnableDebugLogging {
            get {
                return ResourceManager.GetString("AppSettings_Desc_EnableDebugLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the visual size of the user interface. Useful for high-resolution displays or improving readability..
        /// </summary>
        public static string AppSettings_Desc_InterfaceScale {
            get {
                return ResourceManager.GetString("AppSettings_Desc_InterfaceScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the language utilized across the application.
        ///
        ///*Translations may be inaccurate, English is the only officially supported language..
        /// </summary>
        public static string AppSettings_Desc_Language {
            get {
                return ResourceManager.GetString("AppSettings_Desc_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When minimized, the application will be hidden in the system tray instead of remaining on the taskbar..
        /// </summary>
        public static string AppSettings_Desc_MinimizeToTray {
            get {
                return ResourceManager.GetString("AppSettings_Desc_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the application&apos;s current settings and replace them with the factory defaults..
        /// </summary>
        public static string AppSettings_Desc_ResetToFactorySettings {
            get {
                return ResourceManager.GetString("AppSettings_Desc_ResetToFactorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores the main window to its default dimensions and snaps it back to the center of your primary monitor..
        /// </summary>
        public static string AppSettings_Desc_ResetWindowPosition {
            get {
                return ResourceManager.GetString("AppSettings_Desc_ResetWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically launch the application when Windows starts..
        /// </summary>
        public static string AppSettings_Desc_StartWithWindows {
            get {
                return ResourceManager.GetString("AppSettings_Desc_StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes are saved automatically..
        /// </summary>
        public static string AppSettings_Footer_YourChangesAreSavedAutomatically {
            get {
                return ResourceManager.GetString("AppSettings_Footer_YourChangesAreSavedAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string AppSettings_Lbl_AccentColor {
            get {
                return ResourceManager.GetString("AppSettings_Lbl_AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string AppSettings_Lbl_AlwaysOnTop {
            get {
                return ResourceManager.GetString("AppSettings_Lbl_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string AppSettings_Lbl_CheckForUpdates {
            get {
                return ResourceManager.GetString("AppSettings_Lbl_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string AppSettings_Lbl_CheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("AppSettings_Lbl_CheckForUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug logging.
        /// </summary>
        public static string AppSettings_Lbl_EnableDebugLogging {
            get {
                return ResourceManager.GetString("AppSettings_Lbl_EnableDebugLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface scale.
        /// </summary>
        public static string AppSettings_Lbl_InterfaceScale {
            get {
                return ResourceManager.GetString("AppSettings_Lbl_InterfaceScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string AppSettings_Lbl_Language {
            get {
                return ResourceManager.GetString("AppSettings_Lbl_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        public static string AppSettings_Lbl_MinimizeToTray {
            get {
                return ResourceManager.GetString("AppSettings_Lbl_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to factory settings.
        /// </summary>
        public static string AppSettings_Lbl_ResetToFactorySettings {
            get {
                return ResourceManager.GetString("AppSettings_Lbl_ResetToFactorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset window position.
        /// </summary>
        public static string AppSettings_Lbl_ResetWindowPosition {
            get {
                return ResourceManager.GetString("AppSettings_Lbl_ResetWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string AppSettings_Lbl_StartWithWindows {
            get {
                return ResourceManager.GetString("AppSettings_Lbl_StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string AppSettings_Section_Appearance {
            get {
                return ResourceManager.GetString("AppSettings_Section_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Behavior.
        /// </summary>
        public static string AppSettings_Section_ApplicationBehavior {
            get {
                return ResourceManager.GetString("AppSettings_Section_ApplicationBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string AppSettings_Section_Logging {
            get {
                return ResourceManager.GetString("AppSettings_Section_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string AppSettings_Section_Maintenance {
            get {
                return ResourceManager.GetString("AppSettings_Section_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string AppSettings_Section_Updates {
            get {
                return ResourceManager.GetString("AppSettings_Section_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string AppSettings_Title {
            get {
                return ResourceManager.GetString("AppSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Btn_Browse {
            get {
                return ResourceManager.GetString("Btn_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Btn_No {
            get {
                return ResourceManager.GetString("Btn_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Btn_Ok {
            get {
                return ResourceManager.GetString("Btn_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Btn_Yes {
            get {
                return ResourceManager.GetString("Btn_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Logs.
        /// </summary>
        public static string CliLogs_ClearLogs {
            get {
                return ResourceManager.GetString("CliLogs_ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLI Output.
        /// </summary>
        public static string CliLogs_Title {
            get {
                return ResourceManager.GetString("CliLogs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command cannot be empty..
        /// </summary>
        public static string CommandCannotBeEmpty {
            get {
                return ResourceManager.GetString("CommandCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CrashReportWindow_Btn_Close {
            get {
                return ResourceManager.GetString("CrashReportWindow_Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Crash Report.
        /// </summary>
        public static string CrashReportWindow_Btn_SendCrashReport {
            get {
                return ResourceManager.GetString("CrashReportWindow_Btn_SendCrashReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error caused the application to crash..
        /// </summary>
        public static string CrashReportWindow_Desc {
            get {
                return ResourceManager.GetString("CrashReportWindow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string CrashReportWindow_Header_SomethingWentWrong {
            get {
                return ResourceManager.GetString("CrashReportWindow_Header_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string CrashReportWindow_Lbl_Details {
            get {
                return ResourceManager.GetString("CrashReportWindow_Lbl_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Details Placeholder].
        /// </summary>
        public static string CrashReportWindow_Lbl_DetailsPlaceholder {
            get {
                return ResourceManager.GetString("CrashReportWindow_Lbl_DetailsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:.
        /// </summary>
        public static string CrashReportWindow_Lbl_Exception {
            get {
                return ResourceManager.GetString("CrashReportWindow_Lbl_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Exception Message].
        /// </summary>
        public static string CrashReportWindow_Lbl_ExceptionPlaceholder {
            get {
                return ResourceManager.GetString("CrashReportWindow_Lbl_ExceptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File Location:.
        /// </summary>
        public static string CrashReportWindow_Lbl_LogFileLocation {
            get {
                return ResourceManager.GetString("CrashReportWindow_Lbl_LogFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch the report pipeline automatically.
        ///
        ///Please create an issue manually and attach your log file.
        ///
        ///Log Path: {0}
        ///
        ///Error details: {1}.
        /// </summary>
        public static string CrashReportWindow_Msg_SubmitError_Desc {
            get {
                return ResourceManager.GetString("CrashReportWindow_Msg_SubmitError_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | Crash Reporter.
        /// </summary>
        public static string CrashReportWindow_Title {
            get {
                return ResourceManager.GetString("CrashReportWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency downloads complete!.
        /// </summary>
        public static string DependencyDownloadsComplete {
            get {
                return ResourceManager.GetString("DependencyDownloadsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency Manager.
        /// </summary>
        public static string DependencyManager {
            get {
                return ResourceManager.GetString("DependencyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application requires additional components to function correctly. Do you want to download and install them now?.
        /// </summary>
        public static string DependencyService_Msg_DepsFound_Desc {
            get {
                return ResourceManager.GetString("DependencyService_Msg_DepsFound_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies Found.
        /// </summary>
        public static string DependencyService_Msg_DepsFound_Title {
            get {
                return ResourceManager.GetString("DependencyService_Msg_DepsFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required dependency &apos;{0}&apos; is completely unsupported on this machine&apos;s operating platform or architecture..
        /// </summary>
        public static string DependencyService_Msg_IncompatibleDependency_Desc {
            get {
                return ResourceManager.GetString("DependencyService_Msg_IncompatibleDependency_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible Dependency.
        /// </summary>
        public static string DependencyService_Msg_IncompatibleDependency_Title {
            get {
                return ResourceManager.GetString("DependencyService_Msg_IncompatibleDependency_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another installation is currently running on your computer. Please complete or close other installers, then restart {0}..
        /// </summary>
        public static string DependencyService_Msg_InstallationBlocked_Desc {
            get {
                return ResourceManager.GetString("DependencyService_Msg_InstallationBlocked_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Blocked.
        /// </summary>
        public static string DependencyService_Msg_InstallationBlocked_Title {
            get {
                return ResourceManager.GetString("DependencyService_Msg_InstallationBlocked_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more installations require a system reboot to function properly. Would you like to restart your computer now?.
        /// </summary>
        public static string DependencyService_Msg_RestartRequired_Desc {
            get {
                return ResourceManager.GetString("DependencyService_Msg_RestartRequired_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        public static string DependencyService_Msg_RestartRequired_Title {
            get {
                return ResourceManager.GetString("DependencyService_Msg_RestartRequired_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Repak
        ///
        ///Please wait....
        /// </summary>
        public static string DownloadingRepakNNPleaseWait {
            get {
                return ResourceManager.GetString("DownloadingRepakNNPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Retoc
        ///
        ///Please wait....
        /// </summary>
        public static string DownloadingRetocNNPleaseWait {
            get {
                return ResourceManager.GetString("DownloadingRetocNNPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error running command:.
        /// </summary>
        public static string ErrorRunningCommand {
            get {
                return ResourceManager.GetString("ErrorRunningCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target directory does not exist.
        ///
        ///Path: {0}.
        /// </summary>
        public static string FolderService_Msg_DoesNotExist_Desc {
            get {
                return ResourceManager.GetString("FolderService_Msg_DoesNotExist_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open folder: {0}.
        /// </summary>
        public static string FolderService_Msg_FailedToOpen_Desc {
            get {
                return ResourceManager.GetString("FolderService_Msg_FailedToOpen_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;INPUT&gt;.
        /// </summary>
        public static string INPUT {
            get {
                return ResourceManager.GetString("INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input AssetRegistry.bin file.
        /// </summary>
        public static string InputAssetRegistryBinFile {
            get {
                return ResourceManager.GetString("InputAssetRegistryBinFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input directory or .pak.
        /// </summary>
        public static string InputDirectoryOrPak {
            get {
                return ResourceManager.GetString("InputDirectoryOrPak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input reflection data .jmap dump.
        /// </summary>
        public static string InputReflectionDataJmapDump {
            get {
                return ResourceManager.GetString("InputReflectionDataJmapDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input .utoc file containing script objects.
        /// </summary>
        public static string InputUtocFileContainingScriptObjects {
            get {
                return ResourceManager.GetString("InputUtocFileContainingScriptObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input .utoc or directory with multiple .utoc (e.g. Content/Paks/).
        /// </summary>
        public static string InputUtocOrDirectoryWithMultipleUtocEGContentPaks {
            get {
                return ResourceManager.GetString("InputUtocOrDirectoryWithMultipleUtocEGContentPaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands Path.
        /// </summary>
        public static string IoStorePacking_CommandsPath {
            get {
                return ResourceManager.GetString("IoStorePacking_CommandsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooked Files Path (cooked files to be packaged).
        /// </summary>
        public static string IoStorePacking_CookedFilesPathCookedFilesToBePackaged {
            get {
                return ResourceManager.GetString("IoStorePacking_CookedFilesPathCookedFilesToBePackaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Crypto.json.
        /// </summary>
        public static string IoStorePacking_EditCryptoJson {
            get {
                return ResourceManager.GetString("IoStorePacking_EditCryptoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path (for global.utoc).
        /// </summary>
        public static string IoStorePacking_OutputPathForGlobalUtoc {
            get {
                return ResourceManager.GetString("IoStorePacking_OutputPathForGlobalUtoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string IoStorePacking_Pack {
            get {
                return ResourceManager.GetString("IoStorePacking_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageStore Path.
        /// </summary>
        public static string IoStorePacking_PackageStorePath {
            get {
                return ResourceManager.GetString("IoStorePacking_PackageStorePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptObjects Path.
        /// </summary>
        public static string IoStorePacking_ScriptObjectsPath {
            get {
                return ResourceManager.GetString("IoStorePacking_ScriptObjectsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoStore Packing.
        /// </summary>
        public static string IoStorePacking_Title {
            get {
                return ResourceManager.GetString("IoStorePacking_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnrealPak Path (requires Unreal Engine 4.25+).
        /// </summary>
        public static string IoStorePacking_UnrealPakPathRequiresUnrealEngine425 {
            get {
                return ResourceManager.GetString("IoStorePacking_UnrealPakPathRequiresUnrealEngine425", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse input folder.
        /// </summary>
        public static string MainView_BrowseInputFolder {
            get {
                return ResourceManager.GetString("MainView_BrowseInputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse output folder.
        /// </summary>
        public static string MainView_BrowseOutputFolder {
            get {
                return ResourceManager.GetString("MainView_BrowseOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string MainView_Files {
            get {
                return ResourceManager.GetString("MainView_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string MainView_Folders {
            get {
                return ResourceManager.GetString("MainView_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoStore Mode.
        /// </summary>
        public static string MainView_ModeSwitch_IoStoreMode {
            get {
                return ResourceManager.GetString("MainView_ModeSwitch_IoStoreMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Mode.
        /// </summary>
        public static string MainView_ModeSwitch_NormalMode {
            get {
                return ResourceManager.GetString("MainView_ModeSwitch_NormalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repack.
        /// </summary>
        public static string MainView_Repack {
            get {
                return ResourceManager.GetString("MainView_Repack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack.
        /// </summary>
        public static string MainView_Unpack {
            get {
                return ResourceManager.GetString("MainView_Unpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the GitHub repository in your browser..
        /// </summary>
        public static string MainWindow_Btn_OpenTheGitHubRepo {
            get {
                return ResourceManager.GetString("MainWindow_Btn_OpenTheGitHubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you absolutely sure you want to reset all application settings back to factory defaults? This action cannot be undone..
        /// </summary>
        public static string MainWindowFlyoutsView_Msg_ResetToFactorySettings_Desc {
            get {
                return ResourceManager.GetString("MainWindowFlyoutsView_Msg_ResetToFactorySettings_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Reset Settings.
        /// </summary>
        public static string MainWindowFlyoutsView_Msg_ResetToFactorySettings_Title {
            get {
                return ResourceManager.GetString("MainWindowFlyoutsView_Msg_ResetToFactorySettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All application settings have been restored to factory defaults successfully..
        /// </summary>
        public static string MainWindowFlyoutsView_Msg_ResetToFactorySettingsComplete_Desc {
            get {
                return ResourceManager.GetString("MainWindowFlyoutsView_Msg_ResetToFactorySettingsComplete_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Complete.
        /// </summary>
        public static string MainWindowFlyoutsView_Msg_ResetToFactorySettingsComplete_Title {
            get {
                return ResourceManager.GetString("MainWindowFlyoutsView_Msg_ResetToFactorySettingsComplete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while attempting to wipe your configuration profile..
        /// </summary>
        public static string MainWindowFlyoutsView_Msg_ResetToFactorySettingsError_Desc {
            get {
                return ResourceManager.GetString("MainWindowFlyoutsView_Msg_ResetToFactorySettingsError_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update registry startup key: {0}.
        /// </summary>
        public static string MainWindowFlyoutsView_Msg_StartWithWindowsToggleError_Desc {
            get {
                return ResourceManager.GetString("MainWindowFlyoutsView_Msg_StartWithWindowsToggleError_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Dependencies!
        ///
        ///PakMaster will not work without the dependencies..
        /// </summary>
        public static string MissingDependencies {
            get {
                return ResourceManager.GetString("MissingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Msg_Error_Title {
            get {
                return ResourceManager.GetString("Msg_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450.
        /// </summary>
        public static string Num_About_Flyout_Width {
            get {
                return ResourceManager.GetString("Num_About_Flyout_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180.
        /// </summary>
        public static string Num_AppSettings_Btn_CheckForUpdates_Width {
            get {
                return ResourceManager.GetString("Num_AppSettings_Btn_CheckForUpdates_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180.
        /// </summary>
        public static string Num_AppSettings_Btn_ResetToFactorySettings_Width {
            get {
                return ResourceManager.GetString("Num_AppSettings_Btn_ResetToFactorySettings_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450.
        /// </summary>
        public static string Num_AppSettings_Flyout_Width {
            get {
                return ResourceManager.GetString("Num_AppSettings_Flyout_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional output path or stdout if &quot;-&quot; or omitted.
        /// </summary>
        public static string OptionalOutputPathOrStdoutIfOrOmitted {
            get {
                return ResourceManager.GetString("OptionalOutputPathOrStdoutIfOrOmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OUTPUT&gt;.
        /// </summary>
        public static string OUTPUT {
            get {
                return ResourceManager.GetString("OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OUTPUT_DIR&gt;.
        /// </summary>
        public static string OUTPUT_DIR {
            get {
                return ResourceManager.GetString("OUTPUT_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory or .pak.
        /// </summary>
        public static string OutputDirectoryOrPak {
            get {
                return ResourceManager.GetString("OutputDirectoryOrPak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output .utoc.
        /// </summary>
        public static string OutputUtoc {
            get {
                return ResourceManager.GetString("OutputUtoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output .utoc file.
        /// </summary>
        public static string OutputUtocFile {
            get {
                return ResourceManager.GetString("OutputUtocFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PATH&gt;.
        /// </summary>
        public static string PATH {
            get {
                return ResourceManager.GetString("PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repak is missing.
        ///
        ///Would you like to download it now?.
        /// </summary>
        public static string RepakIsMissingNNWouldYouLikeToDownloadItNow {
            get {
                return ResourceManager.GetString("RepakIsMissingNNWouldYouLikeToDownloadItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pak File Version.
        /// </summary>
        public static string RepakSettings_PakVersion {
            get {
                return ResourceManager.GetString("RepakSettings_PakVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string RepakSettings_Read {
            get {
                return ResourceManager.GetString("RepakSettings_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repak Settings.
        /// </summary>
        public static string RepakSettings_Title {
            get {
                return ResourceManager.GetString("RepakSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UE Version.
        /// </summary>
        public static string RepakSettings_UEVersion {
            get {
                return ResourceManager.GetString("RepakSettings_UEVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string RepakSettings_Version {
            get {
                return ResourceManager.GetString("RepakSettings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Feature.
        /// </summary>
        public static string RepakSettings_VersionFeature {
            get {
                return ResourceManager.GetString("RepakSettings_VersionFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string RepakSettings_Write {
            get {
                return ResourceManager.GetString("RepakSettings_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256 bit AES encryption key as base64 or hex string if the pak is encrypted.
        /// </summary>
        public static string RepakView_256BitAESEncryptionKeyAsBase64OrHexStringIfThePakIsEncrypted {
            get {
                return ResourceManager.GetString("RepakView_256BitAESEncryptionKeyAsBase64OrHexStringIfThePakIsEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        public static string RepakView_Compression {
            get {
                return ResourceManager.GetString("RepakView_Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files or directories to include. Can be specified multiple times. If not specified, everything is extracted.
        /// </summary>
        public static string RepakView_FilesOrDirectoriesToIncludeCanBeSpecifiedMultipleTimesIfNotSpecifiedEverythingIsExtracted {
            get {
                return ResourceManager.GetString("RepakView_FilesOrDirectoriesToIncludeCanBeSpecifiedMultipleTimesIfNotSpecifiedEve" +
                        "rythingIsExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Overwrite.
        /// </summary>
        public static string RepakView_ForceOverwrite {
            get {
                return ResourceManager.GetString("RepakView_ForceOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force overwrite existing files/directories.
        /// </summary>
        public static string RepakView_ForceOverwriteExistingFilesDirectories {
            get {
                return ResourceManager.GetString("RepakView_ForceOverwriteExistingFilesDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides normal output such as progress bar and completion status.
        /// </summary>
        public static string RepakView_HidesNormalOutputSuchAsProgressBarAndCompletionStatus {
            get {
                return ResourceManager.GetString("RepakView_HidesNormalOutputSuchAsProgressBarAndCompletionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Pattern.
        /// </summary>
        public static string RepakView_Include {
            get {
                return ResourceManager.GetString("RepakView_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount Point.
        /// </summary>
        public static string RepakView_MountPoint {
            get {
                return ResourceManager.GetString("RepakView_MountPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount point (default: ../../../).
        /// </summary>
        public static string RepakView_MountPointDefault {
            get {
                return ResourceManager.GetString("RepakView_MountPointDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Hash Seed.
        /// </summary>
        public static string RepakView_PathHashSeed {
            get {
                return ResourceManager.GetString("RepakView_PathHashSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path hash seed for &gt;= V10 (default: 0).
        /// </summary>
        public static string RepakView_PathHashSeedForV10Default0 {
            get {
                return ResourceManager.GetString("RepakView_PathHashSeedForV10Default0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to file to read to stdout.
        /// </summary>
        public static string RepakView_PathToFileToReadToStdout {
            get {
                return ResourceManager.GetString("RepakView_PathToFileToReadToStdout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix to strip from entry path (default: ../../../).
        /// </summary>
        public static string RepakView_PrefixToStripFromEntryPathDefault {
            get {
                return ResourceManager.GetString("RepakView_PrefixToStripFromEntryPathDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet.
        /// </summary>
        public static string RepakView_Quiet {
            get {
                return ResourceManager.GetString("RepakView_Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repak Branch.
        /// </summary>
        public static string RepakView_RepakBranch {
            get {
                return ResourceManager.GetString("RepakView_RepakBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strip Prefix.
        /// </summary>
        public static string RepakView_StripPrefix {
            get {
                return ResourceManager.GetString("RepakView_StripPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string RepakView_Verbose {
            get {
                return ResourceManager.GetString("RepakView_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string RepakView_Version {
            get {
                return ResourceManager.GetString("RepakView_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retoc is missing.
        ///
        ///Would you like to download it now?.
        /// </summary>
        public static string RetocIsMissingNNWouldYouLikeToDownloadItNow {
            get {
                return ResourceManager.GetString("RetocIsMissingNNWouldYouLikeToDownloadItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string RetocRepak_AESKey {
            get {
                return ResourceManager.GetString("RetocRepak_AESKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Preview.
        /// </summary>
        public static string RetocRepak_CommandPreview {
            get {
                return ResourceManager.GetString("RetocRepak_CommandPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Command.
        /// </summary>
        public static string RetocRepak_ExecuteCommand {
            get {
                return ResourceManager.GetString("RetocRepak_ExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Chunks.
        /// </summary>
        public static string RetocView_AllChunks {
            get {
                return ResourceManager.GetString("RetocView_AllChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset file name filter.
        /// </summary>
        public static string RetocView_AssetFileNameFilter {
            get {
                return ResourceManager.GetString("RetocView_AssetFileNameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Filter.
        /// </summary>
        public static string RetocView_AssetFilter {
            get {
                return ResourceManager.GetString("RetocView_AssetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default only unique chunks will be listed. --all will also list chunks overriden by patch containers.
        /// </summary>
        public static string RetocView_ByDefaultOnlyUniqueChunksWillBeListedAllWillAlsoListChunksOverridenByPatchContainers {
            get {
                return ResourceManager.GetString("RetocView_ByDefaultOnlyUniqueChunksWillBeListedAllWillAlsoListChunksOverridenByPa" +
                        "tchContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string RetocView_Clear {
            get {
                return ResourceManager.GetString("RetocView_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string RetocView_Command {
            get {
                return ResourceManager.GetString("RetocView_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string RetocView_Debug {
            get {
                return ResourceManager.GetString("RetocView_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug logging.
        /// </summary>
        public static string RetocView_DebugLogging {
            get {
                return ResourceManager.GetString("RetocView_DebugLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not output any files (dry run). Useful for testing conversion.
        /// </summary>
        public static string RetocView_DoNotOutputAnyFilesDryRunUsefulForTestingConversion {
            get {
                return ResourceManager.GetString("RetocView_DoNotOutputAnyFilesDryRunUsefulForTestingConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not run in parallel. Useful for debugging.
        /// </summary>
        public static string RetocView_DoNotRunInParallelUsefulForDebugging {
            get {
                return ResourceManager.GetString("RetocView_DoNotRunInParallelUsefulForDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Run.
        /// </summary>
        public static string RetocView_DryRun {
            get {
                return ResourceManager.GetString("RetocView_DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Version.
        /// </summary>
        public static string RetocView_EngineVersion {
            get {
                return ResourceManager.GetString("RetocView_EngineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string RetocView_File {
            get {
                return ResourceManager.GetString("RetocView_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Folder Paths.
        /// </summary>
        public static string RetocView_FileFolderPaths {
            get {
                return ResourceManager.GetString("RetocView_FileFolderPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string RetocView_Folder {
            get {
                return ResourceManager.GetString("RetocView_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string RetocView_ID {
            get {
                return ResourceManager.GetString("RetocView_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Path.
        /// </summary>
        public static string RetocView_InputPath {
            get {
                return ResourceManager.GetString("RetocView_InputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AES_KEY&gt;.
        /// </summary>
        public static string RetocView_LtAES_KEYGt {
            get {
                return ResourceManager.GetString("RetocView_LtAES_KEYGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Assets.
        /// </summary>
        public static string RetocView_NoAssets {
            get {
                return ResourceManager.GetString("RetocView_NoAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Compress Shaders.
        /// </summary>
        public static string RetocView_NoCompressShaders {
            get {
                return ResourceManager.GetString("RetocView_NoCompressShaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Parallel.
        /// </summary>
        public static string RetocView_NoParallel {
            get {
                return ResourceManager.GetString("RetocView_NoParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Script Objects.
        /// </summary>
        public static string RetocView_NoScriptObjects {
            get {
                return ResourceManager.GetString("RetocView_NoScriptObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shaders.
        /// </summary>
        public static string RetocView_NoShaders {
            get {
                return ResourceManager.GetString("RetocView_NoShaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string RetocView_Options {
            get {
                return ResourceManager.GetString("RetocView_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path.
        /// </summary>
        public static string RetocView_OutputPath {
            get {
                return ResourceManager.GetString("RetocView_OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Container Header Version.
        /// </summary>
        public static string RetocView_OverrideContainerHeaderVersion {
            get {
                return ResourceManager.GetString("RetocView_OverrideContainerHeaderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override TOC Version.
        /// </summary>
        public static string RetocView_OverrideTOCVersion {
            get {
                return ResourceManager.GetString("RetocView_OverrideTOCVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Cell.
        /// </summary>
        public static string RetocView_ScriptCell {
            get {
                return ResourceManager.GetString("RetocView_ScriptCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Command.
        /// </summary>
        public static string RetocView_SelectCommand {
            get {
                return ResourceManager.GetString("RetocView_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show chunk content hash.
        /// </summary>
        public static string RetocView_ShowChunkContentHash {
            get {
                return ResourceManager.GetString("RetocView_ShowChunkContentHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show chunk path.
        /// </summary>
        public static string RetocView_ShowChunkPath {
            get {
                return ResourceManager.GetString("RetocView_ShowChunkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show chunk size.
        /// </summary>
        public static string RetocView_ShowChunkSize {
            get {
                return ResourceManager.GetString("RetocView_ShowChunkSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hash.
        /// </summary>
        public static string RetocView_ShowHash {
            get {
                return ResourceManager.GetString("RetocView_ShowHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Package.
        /// </summary>
        public static string RetocView_ShowPackage {
            get {
                return ResourceManager.GetString("RetocView_ShowPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show package ID.
        /// </summary>
        public static string RetocView_ShowPackageID {
            get {
                return ResourceManager.GetString("RetocView_ShowPackageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show package store entry.
        /// </summary>
        public static string RetocView_ShowPackageStoreEntry {
            get {
                return ResourceManager.GetString("RetocView_ShowPackageStoreEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Path.
        /// </summary>
        public static string RetocView_ShowPath {
            get {
                return ResourceManager.GetString("RetocView_ShowPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Size.
        /// </summary>
        public static string RetocView_ShowSize {
            get {
                return ResourceManager.GetString("RetocView_ShowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Store.
        /// </summary>
        public static string RetocView_ShowStore {
            get {
                return ResourceManager.GetString("RetocView_ShowStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip compression of shader libraries.
        /// </summary>
        public static string RetocView_SkipCompressionOfShaderLibraries {
            get {
                return ResourceManager.GetString("RetocView_SkipCompressionOfShaderLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip conversion of assets.
        /// </summary>
        public static string RetocView_SkipConversionOfAssets {
            get {
                return ResourceManager.GetString("RetocView_SkipConversionOfAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip conversion of shader libraries.
        /// </summary>
        public static string RetocView_SkipConversionOfShaderLibraries {
            get {
                return ResourceManager.GetString("RetocView_SkipConversionOfShaderLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip extraction of script objects.
        /// </summary>
        public static string RetocView_SkipExtractionOfScriptObjects {
            get {
                return ResourceManager.GetString("RetocView_SkipExtractionOfScriptObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string RetocView_Verbose {
            get {
                return ResourceManager.GetString("RetocView_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose logging.
        /// </summary>
        public static string RetocView_VerboseLogging {
            get {
                return ResourceManager.GetString("RetocView_VerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Folder for Output.
        /// </summary>
        public static string SelectAFolderForOutput {
            get {
                return ResourceManager.GetString("SelectAFolderForOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Folder to Pack.
        /// </summary>
        public static string SelectAFolderToPack {
            get {
                return ResourceManager.GetString("SelectAFolderToPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a .pak File.
        /// </summary>
        public static string SelectAPakFile {
            get {
                return ResourceManager.GetString("SelectAPakFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Input File.
        /// </summary>
        public static string SelectInputFile {
            get {
                return ResourceManager.GetString("SelectInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Input Folder.
        /// </summary>
        public static string SelectInputFolder {
            get {
                return ResourceManager.GetString("SelectInputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output File.
        /// </summary>
        public static string SelectOutputFile {
            get {
                return ResourceManager.GetString("SelectOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Folder.
        /// </summary>
        public static string SelectOutputFolder {
            get {
                return ResourceManager.GetString("SelectOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output .pak File.
        /// </summary>
        public static string SelectOutputPakFile {
            get {
                return ResourceManager.GetString("SelectOutputPakFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes applied successfully..
        /// </summary>
        public static string Toast_Desc_ConfigurationSaved {
            get {
                return ResourceManager.GetString("Toast_Desc_ConfigurationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Saved.
        /// </summary>
        public static string Toast_Title_ConfigurationSaved {
            get {
                return ResourceManager.GetString("Toast_Title_ConfigurationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayIcon_Header_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_Header_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Application.
        /// </summary>
        public static string TrayIcon_Header_ShowApplication {
            get {
                return ResourceManager.GetString("TrayIcon_Header_ShowApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string UpdateService_Msg_CheckForUpdates_Title {
            get {
                return ResourceManager.GetString("UpdateService_Msg_CheckForUpdates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re a wizard, harry!
        ///
        ///Latest Version: {0}
        ///Your Version: {1}
        ///
        ///Tell the author they forgot to update the version number..
        /// </summary>
        public static string UpdateService_Msg_EasterEgg_Desc {
            get {
                return ResourceManager.GetString("UpdateService_Msg_EasterEgg_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates: {0}.
        /// </summary>
        public static string UpdateService_Msg_FailedToCheck_Desc {
            get {
                return ResourceManager.GetString("UpdateService_Msg_FailedToCheck_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve valid update information..
        /// </summary>
        public static string UpdateService_Msg_FailedToRetrieve_Desc {
            get {
                return ResourceManager.GetString("UpdateService_Msg_FailedToRetrieve_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available.
        ///
        ///Latest Version: {0}
        ///Your Version: {1}
        ///
        ///Would you like to download the new version?.
        /// </summary>
        public static string UpdateService_Msg_NewVersion_Desc {
            get {
                return ResourceManager.GetString("UpdateService_Msg_NewVersion_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already using the latest version.
        ///
        ///Latest Version: {0}
        ///Your Version: {1}.
        /// </summary>
        public static string UpdateService_Msg_UpToDate_Desc {
            get {
                return ResourceManager.GetString("UpdateService_Msg_UpToDate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open URL: {0}.
        /// </summary>
        public static string UrlService_Msg_FailedToOpenURL_Desc {
            get {
                return ResourceManager.GetString("UrlService_Msg_FailedToOpenURL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UTOC&gt;.
        /// </summary>
        public static string UTOC {
            get {
                return ResourceManager.GetString("UTOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZenTools Settings.
        /// </summary>
        public static string ZenToolsSettings_Title {
            get {
                return ResourceManager.GetString("ZenToolsSettings_Title", resourceCulture);
            }
        }
    }
}
